export const SET_VIDEOS = 'SET_VIDEOS';
export const ADD_VIDEO = 'ADD_VIDEO';
export const REMOVE_VIDEO = 'REMOVE_VIDEO';
export const CLEAR_VIDEO_LIST = 'CLEAR_VIDEO_LIST';
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES';
